// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CartItem represents a single item in the cart
 */
export interface CartItem {
    "product_id": string;
    "name": string;
    "qty": number;
    "price": number;
    "tax_rate": number;

    /**
     * price * qty
     */
    "subtotal": number;

    /**
     * subtotal * tax_rate
     */
    "tax_amount": number;
}

/**
 * Product represents a POS product (max 50 items)
 */
export interface Product {
    "id": string;
    "name": string;
    "price": number;

    /**
     * 0.0 to 1.0 (e.g., 0.05 = 5%)
     */
    "tax_rate": number;

    /**
     * base64 data URL, empty = no image
     */
    "image_data": string;
    "active": boolean;
    "created": string;
}

/**
 * ReportSummary represents a day's or period's sales summary
 */
export interface ReportSummary {
    "date": string;
    "total_transactions": number;
    "total_revenue": number;
    "total_tax": number;
    "upi_transactions": number;
    "cash_transactions": number;
}

/**
 * Settings represents shop configuration (single record)
 */
export interface Settings {
    "id": string;
    "shop_name": string;
    "upi_vpa": string;
    "merchant_name": string;
    "admin_pin": string;
    "theme": string;
    "tax_enabled": boolean;
    "default_tax_rate": number;
    "backup_enabled": boolean;
    "backup_folder": string;
    "backup_retention_days": number;

    /**
     * 0 = primary, 1+ = secondary monitors
     */
    "display_screen": number;

    /**
     * screen name for identification
     */
    "display_screen_name": string;

    /**
     * screen width for identification
     */
    "display_screen_width": number;

    /**
     * screen height for identification
     */
    "display_screen_height": number;

    /**
     * selected printer name for receipts
     */
    "printer_name": string;

    /**
     * auto-print after payment
     */
    "auto_print": boolean;

    /**
     * 58 or 80 (mm) for thermal paper
     */
    "paper_width": number;
}

/**
 * Transaction represents a completed sale
 */
export interface Transaction {
    "id": string;
    "items": CartItem[] | null;
    "subtotal": number;
    "tax_total": number;
    "total": number;

    /**
     * "upi" or "cash"
     */
    "payment_method": string;
    "created": string;
}
