// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./backend/models/models.js";

export function ClearCustomerDisplay(): $CancellablePromise<void> {
    return $Call.ByID(1174768400);
}

export function CloseCustomerDisplay(): $CancellablePromise<void> {
    return $Call.ByID(2672389447);
}

export function ConfirmPayment(): $CancellablePromise<void> {
    return $Call.ByID(295967811);
}

export function CreateProduct(p: models$0.Product): $CancellablePromise<models$0.Product> {
    return $Call.ByID(668623628, p);
}

export function CreateTransaction(t: models$0.Transaction): $CancellablePromise<models$0.Transaction> {
    return $Call.ByID(1755283203, t);
}

export function DeleteProduct(id: string): $CancellablePromise<void> {
    return $Call.ByID(4245649569, id);
}

export function ExportTransactionsCSV(startDate: string, endDate: string): $CancellablePromise<string> {
    return $Call.ByID(3689662970, startDate, endDate);
}

export function ExportTransactionsCSVToDir(startDate: string, endDate: string, dir: string): $CancellablePromise<string> {
    return $Call.ByID(340704382, startDate, endDate, dir);
}

export function GetAvailablePrinters(): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(1404596867);
}

export function GetAvailableScreens(): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(1652254419);
}

export function GetDailyReport(date: string): $CancellablePromise<models$0.ReportSummary> {
    return $Call.ByID(2199403238, date);
}

export function GetProducts(): $CancellablePromise<models$0.Product[] | null> {
    return $Call.ByID(3397715095);
}

export function GetSettings(): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(2554697378);
}

export function GetTransactions(limit: number, offset: number): $CancellablePromise<models$0.Transaction[] | null> {
    return $Call.ByID(96738246, limit, offset);
}

export function GetUPIString(amount: number): $CancellablePromise<string> {
    return $Call.ByID(2226102084, amount);
}

export function GetWeeklyReport(startDate: string): $CancellablePromise<models$0.ReportSummary[] | null> {
    return $Call.ByID(1448145698, startDate);
}

export function IsSetupComplete(): $CancellablePromise<boolean> {
    return $Call.ByID(259807637);
}

export function OpenCustomerDisplay(screenIndex: number): $CancellablePromise<void> {
    return $Call.ByID(2705716685, screenIndex);
}

export function PrintReceipt(t: models$0.Transaction): $CancellablePromise<void> {
    return $Call.ByID(1053202724, t);
}

export function SaveSettings(s: models$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(1949631069, s);
}

export function SelectFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(237181597, title);
}

export function SelectSaveFile(title: string, defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(893202942, title, defaultName);
}

export function SendPaymentMethodToDisplay(method: string): $CancellablePromise<void> {
    return $Call.ByID(738920047, method);
}

export function SendProductsToDisplay(): $CancellablePromise<void> {
    return $Call.ByID(2191768672);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4256893662, app);
}

export function SetBackupSchedule(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2077865576, enabled);
}

export function ShowQROnDisplay(upiString: string, amount: number, vpa: string): $CancellablePromise<void> {
    return $Call.ByID(1604515304, upiString, amount, vpa);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(2987688963);
}

export function Startup(): $CancellablePromise<void> {
    return $Call.ByID(2154875234);
}

export function TriggerBackup(): $CancellablePromise<void> {
    return $Call.ByID(16516297);
}

export function UpdateCustomerDisplay(cartItems: models$0.CartItem[] | null, total: number, taxTotal: number): $CancellablePromise<void> {
    return $Call.ByID(3889504338, cartItems, total, taxTotal);
}

export function UpdateProduct(p: models$0.Product): $CancellablePromise<void> {
    return $Call.ByID(2842109971, p);
}
